const SHEET_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRj2u2mNdNoaxrTnuNN3wcDEEZze0pZJEVlnrihL0UAA3cIyZop2xwRu5rsSgcsnIJ2PWDacDNaSjr9/pub?output=csv";
const CONTENT_TEMPLATE_CANDIDATES = ["Card Back Horizontal Master.png","back.png","Back.png","assets/cards/Card Back Horizontal Master.png","assets/cards/back.png","assets/cards/Back.png"];
const LOGO_TEMPLATE_CANDIDATES = ["Card Front Horizontal Master.png","front.png","Front.png","assets/cards/Card Front Horizontal Master.png","assets/cards/front.png","assets/cards/Front.png"];
const IMAGE_EXTENSIONS = ["png","jpg","jpeg","webp"];
const CATEGORY_PREFIX = {CI:"Check In",CO:"Check Out",FD:"Front Desk",PH:"Telephone",RM:"Rooms",HA:"Hotel Amenities",BV:"Bonvoy",ME:"Meetings/Events",SS:"Service Standards",LU:"Level Up"};
const MODE_NAMES = {standard:"Standard Deck",category:"Pick a Category",elimination:"Category Elimination",challenge:"10-Card Challenge",roundrobin:"Round Robin",host:"Host Mode",passplay:"Pass & Play"};
const MULTIPLAYER_MODES = new Set(["roundrobin","host","passplay"]);
const $ = id => document.getElementById(id);
const els = {
  app:$("app"),controlsPanel:$("controlsPanel"),hideControlsBtn:$("hideControlsBtn"),showControlsBtn:$("showControlsBtn"),contentTemplate:$("contentTemplate"),logoTemplate:$("logoTemplate"),cardShell:$("cardShell"),logoFace:$("logoFace"),headerTapZone:$("headerTapZone"),centerTapZone:$("centerTapZone"),footerTapZone:$("footerTapZone"),cardTitle:$("cardTitle"),cardId:$("cardId"),textLayout:$("textLayout"),scenarioText:$("scenarioText"),answerWrap:$("answerWrap"),answerText:$("answerText"),imageLayout:$("imageLayout"),cardImage:$("cardImage"),imagePrompt:$("imagePrompt"),imageAnswerWrap:$("imageAnswerWrap"),imageAnswerText:$("imageAnswerText"),statusText:$("statusText"),flipBtn:$("flipBtn"),revealBtn:$("revealBtn"),hideBtn:$("hideBtn"),resetDeckBtn:$("resetDeckBtn"),fullscreenBtn:$("fullscreenBtn"),gotoSelect:$("gotoSelect"),gotoBtn:$("gotoBtn"),loadingMask:$("loadingMask"),howToPlayBtn:$("howToPlayBtn"),gameModeBtn:$("gameModeBtn"),modeBanner:$("modeBanner"),modeName:$("modeName"),exitModeBtn:$("exitModeBtn"),howToPlayModal:$("howToPlayModal"),gameModeModal:$("gameModeModal"),categoryModal:$("categoryModal"),categoryGrid:$("categoryGrid"),categoryProgress:$("categoryProgress"),resultModal:$("resultModal"),resultMessage:$("resultMessage"),playAgainBtn:$("playAgainBtn"),challengeScore:$("challengeScore"),challengeProgress:$("challengeProgress"),challengeMissBtn:$("challengeMissBtn"),challengeGotBtn:$("challengeGotBtn"),multiplayerSetupModal:$("multiplayerSetupModal"),setupTitle:$("setupTitle"),playerCount:$("playerCount"),playerNameGrid:$("playerNameGrid"),roundSetupWrap:$("roundSetupWrap"),roundCount:$("roundCount"),hostCardsWrap:$("hostCardsWrap"),hostCardCount:$("hostCardCount"),startMultiplayerBtn:$("startMultiplayerBtn"),gameHud:$("gameHud"),hudTurn:$("hudTurn"),hudScores:$("hudScores"),hudActions:$("hudActions"),touchHint:$("touchHint"),touchHintDismiss:$("touchHintDismiss")
};
const state = {
  deck:[],unusedIndices:[],currentCard:null,currentIndex:-1,isAnimating:false,showingContent:false,answerVisible:false,controlsVisible:true,
  gameMode:"standard",categories:[],eliminationRemaining:[],currentCategory:"",challengeRound:0,challengeScore:0,challengeScored:false,
  immersive:false,fullscreenHintShown:false,pendingMultiplayerMode:"",players:[],scores:[],currentPlayer:0,askerIndex:0,answererIndex:1,
  multiplayerTurn:0,multiplayerTotalTurns:0,hostCardLimit:10,hostRound:0,multiplayerScored:false
};
function parseCsvLine(line){const r=[];let c="",q=false;for(let i=0;i<line.length;i++){const ch=line[i],n=line[i+1];if(ch==='"'){if(q&&n==='"'){c+='"';i++}else q=!q}else if(ch===","&&!q){r.push(c.trim());c=""}else c+=ch}r.push(c.trim());return r}
function categoryFor(card){if(card.Category)return card.Category;const p=String(card.CardID||"").split("-")[0].toUpperCase();return CATEGORY_PREFIX[p]||"Other"}
function normalizeCard(row){const c={CardID:(row.CardID||"").trim(),CardType:((row.CardType||"text").trim().toLowerCase()),Title:(row.Title||"").trim(),Scenario:(row.Scenario||"").trim(),ProfessionalApproach:(row.ProfessionalApproach||"").trim(),ImageURL:(row.ImageURL||"").trim(),ImagePrompt:(row.ImagePrompt||"").trim(),Active:((row.Active||"Y").trim().toUpperCase()),Category:(row.Category||"").trim(),SortOrder:(row.SortOrder||"").trim()};c.ResolvedCategory=categoryFor(c);return c}
function refreshDeckPool(){state.unusedIndices=state.deck.map((_,i)=>i)}
function removeFromUnused(i){state.unusedIndices=state.unusedIndices.filter(x=>x!==i)}
function setStatus(t){els.statusText.textContent=t}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function overflow(el){return el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1}
function fitSingle(el,max,min){el.style.fontSize=max+"px";for(let s=max;s>min&&overflow(el);s-=.5)el.style.fontSize=(s-.5)+"px"}
function fitBlock(block,text,label,maxText,minText,maxLabel,minLabel){let ts=maxText,ls=maxLabel;text.style.fontSize=ts+"px";label.style.fontSize=ls+"px";for(let g=0;overflow(block)&&g<100;g++){if(ts>minText){ts-=.5;text.style.fontSize=ts+"px"}else if(ls>minLabel){ls-=.5;label.style.fontSize=ls+"px"}else break}}
function fitAll(){requestAnimationFrame(()=>{const w=els.cardShell.getBoundingClientRect().width||400;if(els.cardTitle.textContent)fitSingle(els.cardTitle,Math.min(29,Math.max(18,w*.047)),Math.max(12,w*.029));els.cardId.style.fontSize=Math.min(22,Math.max(14,w*.036))+"px";if(!state.currentCard)return;if(state.currentCard.CardType!=="image"){const b=els.textLayout.querySelectorAll(".text-block"),l=els.textLayout.querySelectorAll(".section-label"),mx=Math.min(27,Math.max(16,w*.040)),mn=Math.max(12,w*.028),mlx=Math.min(20,Math.max(13,w*.030)),mln=Math.max(10,w*.023);if(b[0]&&l[0])fitBlock(b[0],els.scenarioText,l[0],mx,mn,mlx,mln);if(b[1]&&l[1])fitBlock(b[1],els.answerText,l[1],mx,mn,mlx,mln)}else{let s=Math.min(23,Math.max(14,w*.038)),m=Math.max(10,w*.024);els.imagePrompt.style.fontSize=els.imageAnswerText.style.fontSize=s+"px";for(let g=0;overflow(els.imageLayout)&&s>m&&g<60;g++){s-=.5;els.imagePrompt.style.fontSize=els.imageAnswerText.style.fontSize=s+"px"}}})}
function showModal(el){if(el)el.hidden=false}
function hideModal(el){if(el)el.hidden=true}
function hideAllModals(){document.querySelectorAll(".modal-backdrop").forEach(m=>m.hidden=true)}
function testImage(src){return new Promise(r=>{const i=new Image();i.onload=()=>r(src);i.onerror=()=>r(null);i.src=src})}
async function firstImage(c){for(const s of c)if(await testImage(s))return s;return""}
async function resolveCardImage(card){if(card.CardType!=="image")return"";const raw=card.CardID.trim(),norm=raw.replace(/[^A-Za-z0-9]/g,""),c=[];for(const e of IMAGE_EXTENSIONS)c.push(`${raw}.${e}`,`${norm}.${e}`,`assets/cards/${raw}.${e}`,`assets/cards/${norm}.${e}`);return firstImage(card.ImageURL?[card.ImageURL,...c]:c)}
function updateChallengePanel(){if(state.gameMode!=="challenge"){els.challengeScore.hidden=true;return}els.challengeProgress.textContent=`Card ${Math.max(1,state.challengeRound)} of 10 • Score ${state.challengeScore}`;els.challengeScore.hidden=!state.answerVisible||state.challengeScored}
function updateHud(){const multi=MULTIPLAYER_MODES.has(state.gameMode);els.gameHud.hidden=!multi;document.body.classList.toggle("has-game-hud",multi);if(!multi)return;els.hudScores.innerHTML=state.players.map((p,i)=>`<span class="score-chip ${activeScoreIndex()===i?'active':''}">${escapeHtml(p)}: ${state.scores[i]||0}</span>`).join("");if(state.gameMode==="roundrobin")els.hudTurn.textContent=`${state.players[state.currentPlayer]}'s turn • ${Math.min(state.multiplayerTurn+1,state.multiplayerTotalTurns)} of ${state.multiplayerTotalTurns}`;else if(state.gameMode==="passplay")els.hudTurn.textContent=`${state.players[state.askerIndex]} asks ${state.players[state.answererIndex]} • ${Math.min(state.multiplayerTurn+1,state.multiplayerTotalTurns)} of ${state.multiplayerTotalTurns}`;else els.hudTurn.textContent=`Host Mode • Card ${Math.min(state.hostRound,state.hostCardLimit)} of ${state.hostCardLimit}`;renderHudActions()}
function activeScoreIndex(){if(state.gameMode==="roundrobin")return state.currentPlayer;if(state.gameMode==="passplay")return state.answererIndex;return -1}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function renderHudActions(){els.hudActions.innerHTML="";if(!MULTIPLAYER_MODES.has(state.gameMode)||!state.currentCard)return;if(!state.answerVisible){els.hudActions.innerHTML='<button type="button" disabled>Reveal answer to score</button>';return}if(state.multiplayerScored)return;if(state.gameMode==="host"){const wrap=document.createElement("div");wrap.className="host-score-grid";state.players.forEach((p,i)=>{const b=document.createElement("button");b.type="button";b.textContent=`${p} +1`;b.onclick=()=>scoreHost(i);wrap.appendChild(b)});const no=document.createElement("button");no.type="button";no.textContent="No Point";no.onclick=()=>scoreHost(-1);wrap.appendChild(no);els.hudActions.appendChild(wrap)}else{const miss=document.createElement("button");miss.type="button";miss.textContent="Missed It";miss.onclick=()=>scoreMultiplayer(false);const got=document.createElement("button");got.type="button";got.textContent="Got It";got.onclick=()=>scoreMultiplayer(true);els.hudActions.append(miss,got)}}
function hideAnswer(){els.answerWrap.classList.add("hidden");els.imageAnswerWrap.classList.add("hidden");state.answerVisible=false;els.revealBtn.disabled=!state.currentCard||!state.currentCard.ProfessionalApproach||state.isAnimating||!state.showingContent;els.hideBtn.disabled=true;updateChallengePanel();updateHud();fitAll()}
function showAnswer(){if(!state.currentCard||!state.currentCard.ProfessionalApproach||state.isAnimating||!state.showingContent)return;(state.currentCard.CardType==="image"?els.imageAnswerWrap:els.answerWrap).classList.remove("hidden");state.answerVisible=true;els.revealBtn.disabled=true;els.hideBtn.disabled=false;updateChallengePanel();updateHud();fitAll()}
function toggleAnswer(){state.answerVisible?hideAnswer():showAnswer()}
async function renderCard(card){state.currentCard=card;state.answerVisible=false;state.challengeScored=false;state.multiplayerScored=false;els.cardTitle.textContent=card.Title;els.cardId.textContent=card.CardID;els.scenarioText.textContent=card.Scenario||"";els.answerText.textContent=els.imageAnswerText.textContent=card.ProfessionalApproach||"";els.answerWrap.classList.add("hidden");els.imageAnswerWrap.classList.add("hidden");els.imagePrompt.textContent="";els.cardImage.removeAttribute("src");if(card.CardType==="image"){els.textLayout.style.display="none";els.imageLayout.style.display="flex";const src=await resolveCardImage(card);if(src)els.cardImage.src=src;els.imagePrompt.textContent=card.ImagePrompt||""}else{els.textLayout.style.display="grid";els.imageLayout.style.display="none"}els.hideBtn.disabled=true;updateChallengePanel();updateHud();fitAll()}
async function showCardByIndex(index,label="Showing"){if(!state.deck.length||state.isAnimating||index<0||index>=state.deck.length)return;state.isAnimating=true;state.currentIndex=index;[els.flipBtn,els.revealBtn,els.hideBtn,els.gotoBtn].forEach(e=>e.disabled=true);const card=state.deck[index];removeFromUnused(index);if(state.showingContent){setStatus("Returning to front…");els.cardShell.classList.remove("show-content");state.showingContent=false;await wait(650)}setStatus("Flipping card…");await renderCard(card);await wait(120);els.cardShell.classList.add("show-content");state.showingContent=true;fitAll();await wait(700);state.isAnimating=false;els.flipBtn.disabled=false;els.revealBtn.disabled=!card.ProfessionalApproach;els.gotoBtn.disabled=state.gameMode!=="standard"||!els.gotoSelect.value;const cat=card.ResolvedCategory?` • ${card.ResolvedCategory}`:"";if(state.gameMode==="challenge")setStatus(`Challenge ${state.challengeRound}/10${cat} • ${card.CardID}`);else if(MULTIPLAYER_MODES.has(state.gameMode))setStatus(`${MODE_NAMES[state.gameMode]}${cat} • ${card.CardID}`);else setStatus(`${label} ${card.CardID}${cat}`);updateModeControls();updateHud()}
function randomIndexFrom(indices){return indices.length?indices[Math.floor(Math.random()*indices.length)]:-1}
function pickRandomIndex(){if(!state.unusedIndices.length)refreshDeckPool();return randomIndexFrom(state.unusedIndices)}
function availableIndicesForCategory(cat){let x=state.unusedIndices.filter(i=>state.deck[i].ResolvedCategory===cat);if(!x.length)x=state.deck.map((c,i)=>c.ResolvedCategory===cat?i:-1).filter(i=>i>=0);return x}
async function flipRandomCard(){const i=pickRandomIndex();if(i>=0)await showCardByIndex(i)}
async function drawFromCategory(cat){hideModal(els.categoryModal);state.currentCategory=cat;const i=randomIndexFrom(availableIndicesForCategory(cat));if(i<0){setStatus(`No active cards found for ${cat}.`);return}if(state.gameMode==="elimination")state.eliminationRemaining=state.eliminationRemaining.filter(c=>c!==cat);await showCardByIndex(i,cat)}
function renderCategoryPicker(){const elim=state.gameMode==="elimination";els.categoryGrid.innerHTML="";state.categories.forEach(cat=>{const b=document.createElement("button");b.type="button";b.className="category-choice";b.textContent=cat;const done=elim&&!state.eliminationRemaining.includes(cat);if(done){b.disabled=true;b.classList.add("done")}else b.onclick=()=>drawFromCategory(cat);els.categoryGrid.appendChild(b)});els.categoryProgress.textContent=elim?`${state.categories.length-state.eliminationRemaining.length} of ${state.categories.length} categories completed`:"Choose any category for the next card."}
function openCategoryPicker(){if(!state.categories.length){setStatus("No categories were found in the deck.");return}if(state.gameMode==="elimination"&&!state.eliminationRemaining.length){completeElimination();return}renderCategoryPicker();showModal(els.categoryModal)}
function updateModeControls(){const m=state.gameMode;els.modeBanner.hidden=m==="standard";els.modeName.textContent=MODE_NAMES[m]||"Standard Deck";els.gotoSelect.disabled=m!=="standard";els.gotoBtn.disabled=m!=="standard"||!els.gotoSelect.value;if(m==="standard")els.flipBtn.textContent="Flip Card (Next)";else if(m==="category"||m==="elimination")els.flipBtn.textContent=m==="elimination"&&!state.eliminationRemaining.length?"Finish Game":"Choose Category";else els.flipBtn.textContent="Next Card";updateChallengePanel();updateHud()}
function clearCard(){state.currentCard=null;state.currentIndex=-1;state.showingContent=false;state.answerVisible=false;[els.cardTitle,els.cardId,els.scenarioText,els.answerText,els.imageAnswerText,els.imagePrompt].forEach(e=>e.textContent="");els.cardImage.removeAttribute("src");els.textLayout.style.display="grid";els.imageLayout.style.display="none";els.answerWrap.classList.add("hidden");els.imageAnswerWrap.classList.add("hidden");els.cardShell.classList.remove("show-content");els.revealBtn.disabled=els.hideBtn.disabled=true}
function resetModeState(){state.currentCategory="";state.challengeRound=0;state.challengeScore=0;state.challengeScored=false;state.eliminationRemaining=[...state.categories];state.players=[];state.scores=[];state.multiplayerTurn=0;state.multiplayerTotalTurns=0;state.hostRound=0;state.multiplayerScored=false;state.currentPlayer=0;state.askerIndex=0;state.answererIndex=1}
async function startMode(mode){hideAllModals();state.gameMode=mode;refreshDeckPool();clearCard();resetModeState();updateModeControls();if(mode==="standard")setStatus("Standard Deck. Tap the card or use Flip Card (Next).");else if(mode==="category"){setStatus("Pick a category to begin.");openCategoryPicker()}else if(mode==="elimination"){setStatus("Complete one card from every category.");openCategoryPicker()}else if(mode==="challenge"){state.challengeRound=1;state.challengeScore=0;setStatus("10-Card Challenge starting…");await flipRandomCard()}}
function openMultiplayerSetup(mode){state.pendingMultiplayerMode=mode;els.setupTitle.textContent=MODE_NAMES[mode]+" Setup";els.roundSetupWrap.hidden=mode==="host";els.hostCardsWrap.hidden=mode!=="host";renderPlayerInputs();hideModal(els.gameModeModal);showModal(els.multiplayerSetupModal)}
function renderPlayerInputs(){const n=Number(els.playerCount.value)||2;const old=[...els.playerNameGrid.querySelectorAll("input")].map(i=>i.value);els.playerNameGrid.innerHTML="";for(let i=0;i<n;i++){const row=document.createElement("div");row.className="player-name-row";const label=document.createElement("label");label.textContent=`Player ${i+1}`;label.htmlFor=`playerName${i}`;const input=document.createElement("input");input.id=`playerName${i}`;input.maxLength=18;input.placeholder=`Player ${i+1}`;input.value=old[i]||"";row.append(label,input);els.playerNameGrid.appendChild(row)}}
async function startMultiplayer(){const mode=state.pendingMultiplayerMode;if(!MULTIPLAYER_MODES.has(mode))return;state.players=[...els.playerNameGrid.querySelectorAll("input")].map((i,n)=>i.value.trim()||`Player ${n+1}`);state.scores=state.players.map(()=>0);state.gameMode=mode;refreshDeckPool();clearCard();state.multiplayerTurn=0;state.currentPlayer=0;state.askerIndex=0;state.answererIndex=state.players.length>1?1:0;state.multiplayerScored=false;if(mode==="host"){state.hostCardLimit=Number(els.hostCardCount.value)||10;state.hostRound=1}else{const rounds=Number(els.roundCount.value)||2;state.multiplayerTotalTurns=rounds*state.players.length}hideAllModals();updateModeControls();await flipRandomCard()}
async function scoreMultiplayer(got){if(!state.answerVisible||state.multiplayerScored)return;state.multiplayerScored=true;const idx=state.gameMode==="roundrobin"?state.currentPlayer:state.answererIndex;if(got)state.scores[idx]++;updateHud();await wait(500);state.multiplayerTurn++;if(state.multiplayerTurn>=state.multiplayerTotalTurns){completeMultiplayer();return}if(state.gameMode==="roundrobin")state.currentPlayer=(state.currentPlayer+1)%state.players.length;else{state.askerIndex=state.answererIndex;state.answererIndex=(state.answererIndex+1)%state.players.length}updateHud();await flipRandomCard()}
async function scoreHost(playerIndex){if(!state.answerVisible||state.multiplayerScored)return;state.multiplayerScored=true;if(playerIndex>=0)state.scores[playerIndex]++;updateHud();await wait(500);if(state.hostRound>=state.hostCardLimit){completeMultiplayer();return}state.hostRound++;updateHud();await flipRandomCard()}
function winnerText(){const max=Math.max(...state.scores);const winners=state.players.filter((_,i)=>state.scores[i]===max);return winners.length===1?`${winners[0]} wins with ${max} point${max===1?"":"s"}!`:`Tie: ${winners.join(" & ")} with ${max} point${max===1?"":"s"} each!`}
function completeMultiplayer(){els.resultMessage.innerHTML=`<strong>${winnerText()}</strong><br><br>${state.players.map((p,i)=>`${escapeHtml(p)}: ${state.scores[i]}`).join(" • ")}`;showModal(els.resultModal)}
function completeElimination(){els.resultMessage.textContent=`You completed all ${state.categories.length} categories!`;showModal(els.resultModal)}
async function scoreChallenge(got){if(state.gameMode!=="challenge"||!state.answerVisible||state.challengeScored)return;state.challengeScored=true;if(got)state.challengeScore++;updateChallengePanel();if(state.challengeRound>=10){await wait(500);els.resultMessage.textContent=`Final score: ${state.challengeScore} out of 10.`;showModal(els.resultModal);return}state.challengeRound++;await wait(500);await flipRandomCard()}
async function nextAction(){if(state.isAnimating)return;const m=state.gameMode;if(m==="standard"){await flipRandomCard();return}if(m==="category"||m==="elimination"){openCategoryPicker();return}if(m==="challenge"){if(!state.currentCard){state.challengeRound=1;await flipRandomCard()}else if(state.answerVisible&&!state.challengeScored)setStatus("Score this card with Got It or Missed It to continue.");else if(!state.answerVisible)setStatus("Reveal and score this card before moving on.");return}if(MULTIPLAYER_MODES.has(m)){if(!state.currentCard){await flipRandomCard();return}if(!state.answerVisible)setStatus("Reveal the Professional Approach, then score the player.");else if(!state.multiplayerScored)setStatus("Score this card before moving on.")}}
async function resetDeck(){refreshDeckPool();clearCard();if(state.gameMode==="standard"){setStatus("Deck reset. Tap the card or use Flip Card (Next) to start.");return}if(state.gameMode==="category"||state.gameMode==="elimination"){if(state.gameMode==="elimination")state.eliminationRemaining=[...state.categories];setStatus("Game reset. Choose a category.");openCategoryPicker();return}if(state.gameMode==="challenge"){state.challengeRound=1;state.challengeScore=0;await flipRandomCard();return}if(MULTIPLAYER_MODES.has(state.gameMode)){state.scores=state.players.map(()=>0);state.multiplayerTurn=0;state.currentPlayer=0;state.askerIndex=0;state.answererIndex=state.players.length>1?1:0;if(state.gameMode==="host")state.hostRound=1;await flipRandomCard()}}
function setControlsVisible(v){state.controlsVisible=v;els.controlsPanel.hidden=!v;els.showControlsBtn.hidden=v;els.app.classList.toggle("controls-hidden",!v);fitAll()}
function showTouchHintOnce(){if(state.fullscreenHintShown)return;state.fullscreenHintShown=true;els.touchHint.hidden=false}
async function enterMobileImmersive(){state.immersive=true;document.body.classList.add("immersive-mobile");setControlsVisible(false);els.fullscreenBtn.textContent="Exit Full Screen";showTouchHintOnce();fitAll()}
async function exitMobileImmersive(){state.immersive=false;document.body.classList.remove("immersive-mobile");setControlsVisible(true);els.fullscreenBtn.textContent="Full Screen";fitAll()}
async function toggleFullscreen(){const mobile=window.matchMedia("(max-width: 720px)").matches;if(mobile){state.immersive?await exitMobileImmersive():await enterMobileImmersive();return}try{if(document.fullscreenElement)await document.exitFullscreen();else{await document.documentElement.requestFullscreen();showTouchHintOnce()}}catch(e){setStatus("Full Screen is not available in this browser.")}els.fullscreenBtn.textContent=document.fullscreenElement?"Exit Full Screen":"Full Screen"}
async function loadSheetData(){const r=await fetch(SHEET_URL);if(!r.ok)throw Error(r.status);const lines=(await r.text()).replace(/^\uFEFF/,"").replace(/\r\n/g,"\n").replace(/\r/g,"\n").trim().split("\n").filter(Boolean),h=parseCsvLine(lines[0]);return lines.slice(1).map(l=>{const v=parseCsvLine(l),o={};h.forEach((x,i)=>o[x]=v[i]||"");return normalizeCard(o)}).filter(c=>c.Active==="Y"&&c.CardID&&c.Title)}
function populateGotoMenu(){els.gotoSelect.innerHTML='<option value="">Go to card…</option>';[...state.deck].sort((a,b)=>(Number(a.SortOrder)||999999)-(Number(b.SortOrder)||999999)||a.CardID.localeCompare(b.CardID)).forEach(c=>{const o=document.createElement("option");o.value=c.CardID;o.textContent=`${c.CardID} — ${c.Title}`;els.gotoSelect.appendChild(o)})}
async function goToSelectedCard(){const i=state.deck.findIndex(c=>c.CardID===els.gotoSelect.value);if(i>=0&&!state.isAnimating)await showCardByIndex(i)}
function key(e,cb){if(e.key==="Enter"||e.key===" "){e.preventDefault();cb()}}
function wire(){els.flipBtn.onclick=nextAction;els.revealBtn.onclick=showAnswer;els.hideBtn.onclick=hideAnswer;els.resetDeckBtn.onclick=resetDeck;els.fullscreenBtn.onclick=toggleFullscreen;els.gotoBtn.onclick=goToSelectedCard;els.gotoSelect.onchange=()=>els.gotoBtn.disabled=state.gameMode!=="standard"||!els.gotoSelect.value||state.isAnimating;els.hideControlsBtn.onclick=()=>setControlsVisible(false);els.showControlsBtn.onclick=()=>state.immersive?exitMobileImmersive():setControlsVisible(true);els.logoFace.onclick=nextAction;els.headerTapZone.onclick=els.footerTapZone.onclick=nextAction;els.centerTapZone.onclick=toggleAnswer;[[els.logoFace,nextAction],[els.headerTapZone,nextAction],[els.footerTapZone,nextAction],[els.centerTapZone,toggleAnswer]].forEach(([e,c])=>e.onkeydown=x=>key(x,c));els.howToPlayBtn.onclick=()=>showModal(els.howToPlayModal);els.gameModeBtn.onclick=()=>showModal(els.gameModeModal);els.exitModeBtn.onclick=()=>startMode("standard");els.challengeGotBtn.onclick=()=>scoreChallenge(true);els.challengeMissBtn.onclick=()=>scoreChallenge(false);els.playAgainBtn.onclick=()=>{hideModal(els.resultModal);if(MULTIPLAYER_MODES.has(state.gameMode))openMultiplayerSetup(state.gameMode);else startMode(state.gameMode)};els.playerCount.onchange=renderPlayerInputs;els.startMultiplayerBtn.onclick=startMultiplayer;els.touchHintDismiss.onclick=()=>els.touchHint.hidden=true;document.querySelectorAll(".mode-choice").forEach(b=>b.onclick=()=>{const m=b.dataset.mode;if(MULTIPLAYER_MODES.has(m))openMultiplayerSetup(m);else startMode(m)});document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>hideModal($(b.dataset.close)));document.querySelectorAll(".modal-backdrop").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.hidden=true}));document.addEventListener("keydown",e=>{if(e.key==="Escape")hideAllModals()});document.addEventListener("fullscreenchange",()=>{els.fullscreenBtn.textContent=document.fullscreenElement?"Exit Full Screen":"Full Screen";if(document.fullscreenElement)showTouchHintOnce();setTimeout(fitAll,50)});let t;window.onresize=()=>{clearTimeout(t);t=setTimeout(fitAll,120)};window.addEventListener("orientationchange",()=>setTimeout(fitAll,250))}
async function init(){wire();renderPlayerInputs();const [back,front]=await Promise.all([firstImage(CONTENT_TEMPLATE_CANDIDATES),firstImage(LOGO_TEMPLATE_CANDIDATES)]);if(back)els.contentTemplate.src=back;if(front)els.logoTemplate.src=front;try{state.deck=await loadSheetData();state.categories=[...new Set(state.deck.map(c=>c.ResolvedCategory).filter(Boolean))].sort((a,b)=>a.localeCompare(b));state.eliminationRemaining=[...state.categories];refreshDeckPool();populateGotoMenu();if(!state.deck.length){setStatus("No active cards found. Check your Google Sheet and Active column.");return}els.gotoBtn.disabled=true;updateModeControls();setStatus("Ready. Tap the card or use Flip Card (Next) to start.")}catch(e){console.error(e);setStatus("Could not load Google Sheet. Check your published CSV link.")}finally{els.loadingMask.style.display="none"}}
init();